services:
  db:
    image: postgres:18.2
    hostname: db
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 5s
      timeout: 2s
      retries: 20
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  server:
    image: ghcr.io/forge34/messaging-app-frontend:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db
      - PORT=3000
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  pgdata: {}
