packages:
  - packages/*
  - apps/*

catalogs:
  prisma:
    prisma: latest

ignoredBuiltDependencies:
  - prisma-zod-generator

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
