/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppUsersRouteRouteImport } from './routes/app/users/route'
import { Route as AppConversationsRouteRouteImport } from './routes/app/conversations/route'
import { Route as AppUsersProfileRouteImport } from './routes/app/users/profile'
import { Route as AppConversationsAtmeRouteImport } from './routes/app/conversations/@me'
import { Route as AppConversationsConversationIdRouteImport } from './routes/app/conversations/$conversationId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppUsersRouteRoute = AppUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConversationsRouteRoute = AppConversationsRouteRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersProfileRoute = AppUsersProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppConversationsAtmeRoute = AppConversationsAtmeRouteImport.update({
  id: '/@me',
  path: '/@me',
  getParentRoute: () => AppConversationsRouteRoute,
} as any)
const AppConversationsConversationIdRoute =
  AppConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AppConversationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/conversations': typeof AppConversationsRouteRouteWithChildren
  '/app/users': typeof AppUsersRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/app/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/app/conversations/@me': typeof AppConversationsAtmeRoute
  '/app/users/profile': typeof AppUsersProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/conversations': typeof AppConversationsRouteRouteWithChildren
  '/app/users': typeof AppUsersRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/app/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/app/conversations/@me': typeof AppConversationsAtmeRoute
  '/app/users/profile': typeof AppUsersProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/conversations': typeof AppConversationsRouteRouteWithChildren
  '/app/users': typeof AppUsersRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/app/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/app/conversations/@me': typeof AppConversationsAtmeRoute
  '/app/users/profile': typeof AppUsersProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/conversations'
    | '/app/users'
    | '/login'
    | '/signup'
    | '/app/conversations/$conversationId'
    | '/app/conversations/@me'
    | '/app/users/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/conversations'
    | '/app/users'
    | '/login'
    | '/signup'
    | '/app/conversations/$conversationId'
    | '/app/conversations/@me'
    | '/app/users/profile'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/app/conversations'
    | '/app/users'
    | '/_auth/login'
    | '/_auth/signup'
    | '/app/conversations/$conversationId'
    | '/app/conversations/@me'
    | '/app/users/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/conversations': {
      id: '/app/conversations'
      path: '/conversations'
      fullPath: '/app/conversations'
      preLoaderRoute: typeof AppConversationsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users/profile': {
      id: '/app/users/profile'
      path: '/profile'
      fullPath: '/app/users/profile'
      preLoaderRoute: typeof AppUsersProfileRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/app/conversations/@me': {
      id: '/app/conversations/@me'
      path: '/@me'
      fullPath: '/app/conversations/@me'
      preLoaderRoute: typeof AppConversationsAtmeRouteImport
      parentRoute: typeof AppConversationsRouteRoute
    }
    '/app/conversations/$conversationId': {
      id: '/app/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/app/conversations/$conversationId'
      preLoaderRoute: typeof AppConversationsConversationIdRouteImport
      parentRoute: typeof AppConversationsRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AppConversationsRouteRouteChildren {
  AppConversationsConversationIdRoute: typeof AppConversationsConversationIdRoute
  AppConversationsAtmeRoute: typeof AppConversationsAtmeRoute
}

const AppConversationsRouteRouteChildren: AppConversationsRouteRouteChildren = {
  AppConversationsConversationIdRoute: AppConversationsConversationIdRoute,
  AppConversationsAtmeRoute: AppConversationsAtmeRoute,
}

const AppConversationsRouteRouteWithChildren =
  AppConversationsRouteRoute._addFileChildren(
    AppConversationsRouteRouteChildren,
  )

interface AppUsersRouteRouteChildren {
  AppUsersProfileRoute: typeof AppUsersProfileRoute
}

const AppUsersRouteRouteChildren: AppUsersRouteRouteChildren = {
  AppUsersProfileRoute: AppUsersProfileRoute,
}

const AppUsersRouteRouteWithChildren = AppUsersRouteRoute._addFileChildren(
  AppUsersRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppConversationsRouteRoute: typeof AppConversationsRouteRouteWithChildren
  AppUsersRouteRoute: typeof AppUsersRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppConversationsRouteRoute: AppConversationsRouteRouteWithChildren,
  AppUsersRouteRoute: AppUsersRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
