/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppConversationsRouteRouteImport } from './routes/app/conversations/route'
import { Route as AppConversationsIdRouteImport } from './routes/app/conversations/$id'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppConversationsRouteRoute = AppConversationsRouteRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConversationsIdRoute = AppConversationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppConversationsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/conversations': typeof AppConversationsRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/app/profile': typeof AppProfileRoute
  '/app/conversations/$id': typeof AppConversationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/conversations': typeof AppConversationsRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/app/profile': typeof AppProfileRoute
  '/app/conversations/$id': typeof AppConversationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/conversations': typeof AppConversationsRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/app/profile': typeof AppProfileRoute
  '/app/conversations/$id': typeof AppConversationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/conversations'
    | '/login'
    | '/signup'
    | '/app/profile'
    | '/app/conversations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/conversations'
    | '/login'
    | '/signup'
    | '/app/profile'
    | '/app/conversations/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/app/conversations'
    | '/_auth/login'
    | '/_auth/signup'
    | '/app/profile'
    | '/app/conversations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/conversations': {
      id: '/app/conversations'
      path: '/conversations'
      fullPath: '/app/conversations'
      preLoaderRoute: typeof AppConversationsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/conversations/$id': {
      id: '/app/conversations/$id'
      path: '/$id'
      fullPath: '/app/conversations/$id'
      preLoaderRoute: typeof AppConversationsIdRouteImport
      parentRoute: typeof AppConversationsRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AppConversationsRouteRouteChildren {
  AppConversationsIdRoute: typeof AppConversationsIdRoute
}

const AppConversationsRouteRouteChildren: AppConversationsRouteRouteChildren = {
  AppConversationsIdRoute: AppConversationsIdRoute,
}

const AppConversationsRouteRouteWithChildren =
  AppConversationsRouteRoute._addFileChildren(
    AppConversationsRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppConversationsRouteRoute: typeof AppConversationsRouteRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppConversationsRouteRoute: AppConversationsRouteRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
