on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages + client
        run: pnpm build:packages && pnpm build:client
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: apps/client/dist

      - name: Clean old client files
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: rm -rf /var/www/chat-app/*

      - name: Deploy to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "apps/client/dist/*"
          target: "/var/www/chat-app/"
          strip_components: 3

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: sudo systemctl reload nginx
